@extends('layouts.app')
@push('styles')<style>.track-card{background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.08);border-radius:16px}.track-step{position:relative;padding:0 0 24px 38px}.track-step:before{content:'';position:absolute;left:11px;top:22px;bottom:0;width:2px;background:rgba(255,255,255,.12)}.track-step:last-child:before{display:none}.track-dot{position:absolute;left:0;top:2px;width:24px;height:24px;border-radius:50%;display:grid;place-items:center;background:#312e81;color:#fff;font-size:.7rem}.track-step.done .track-dot{background:#10b981}.track-step.current .track-dot{background:#3b82f6;box-shadow:0 0 0 6px rgba(59,130,246,.15)}#shipmentMap{height:430px;border-radius:16px;background:#0b0617}.map-wrap{position:relative;overflow:hidden}.map-legend{position:absolute;z-index:500;left:12px;bottom:12px;background:rgba(15,8,30,.9);color:#fff;padding:9px 12px;border-radius:10px;font-size:.75rem}.ship-marker{font-size:25px;filter:drop-shadow(0 3px 5px #000)}</style>@endpush
@section('content')
@php $steps=['pending'=>'Shipment tercatat','loading'=>'Kargo dimuat','departed'=>'Berangkat','in_transit'=>'Dalam perjalanan','arrived'=>'Tiba di pelabuhan','delivered'=>'Kargo diterima'];$current=array_search($shipment->status,array_keys($steps));$current=$current===false?-1:$current; @endphp
<div class="container-fluid py-4"><a href="{{ route('shipments.index') }}" class="text-muted text-decoration-none">← Kembali ke monitoring</a>
 <div class="d-flex justify-content-between align-items-start flex-wrap gap-3 my-4"><div><h1 class="h3 text-white fw-bold">Shipment Detail {{ $shipment->tracking_number }} <span class="badge bg-secondary fs-6">Simulated Route</span></h1><p class="text-muted mb-1">{{ $shipment->originCountry?->name }} → {{ $shipment->destinationCountry?->name }}</p><small class="text-warning">Peta menunjukkan estimasi simulasi, bukan lokasi GPS/AIS langsung.</small></div><span class="badge bg-primary fs-6">{{ ucwords(str_replace('_',' ',$shipment->status)) }}</span></div>
 <div class="row g-4"><div class="col-lg-8"><div class="track-card p-4 mb-4"><div class="d-flex justify-content-between mb-2"><strong class="text-white">Progress perjalanan</strong><strong class="text-primary">{{ $shipment->progress }}%</strong></div><div class="progress" style="height:12px"><div class="progress-bar progress-bar-striped progress-bar-animated" style="width:{{ $shipment->progress }}%"></div></div></div><div class="track-card map-wrap"><div id="shipmentMap"></div><div class="map-legend"><strong>🚢 {{ $shipment->vessel?->name ?? 'Posisi belum tersedia' }}</strong>@if($shipment->vessel)<br>{{ $shipment->vessel->speed }} knot · Haluan {{ $shipment->vessel->heading }}°@endif</div></div></div>
 <div class="col-lg-4"><div class="track-card p-4 mb-4"><h5 class="text-white mb-4">Timeline</h5>@foreach($steps as $key=>$label)@php $i=$loop->index;$done=$i<$current||$shipment->status==='delivered';$active=$i===$current;@endphp<div class="track-step {{ $done?'done':'' }} {{ $active?'current':'' }}"><span class="track-dot">{{ $done?'✓':$i+1 }}</span><strong class="text-white d-block">{{ $label }}</strong><small class="text-muted">{{ $active?'Status saat ini':($done?'Selesai':'Menunggu') }}</small></div>@endforeach</div><div class="track-card p-4"><h5 class="text-white mb-3">Informasi perjalanan</h5><dl class="row small mb-0"><dt class="col-5 text-muted">Asal</dt><dd class="col-7 text-white">{{ $shipment->originPort?->name ?? $shipment->originCountry?->name }}</dd><dt class="col-5 text-muted">Tujuan</dt><dd class="col-7 text-white">{{ $shipment->destinationPort?->name ?? $shipment->destinationCountry?->name }}</dd><dt class="col-5 text-muted">Berangkat</dt><dd class="col-7 text-white">{{ $shipment->departure_at?->format('d M Y H:i') ?? '—' }}</dd><dt class="col-5 text-muted">ETA</dt><dd class="col-7 text-white">{{ $shipment->estimated_arrival?->format('d M Y H:i') ?? '—' }}</dd><dt class="col-5 text-muted">Jarak</dt><dd class="col-7 text-white">{{ number_format($shipment->distance ?? 0) }} km</dd></dl></div></div></div>
</div>
@endsection
@push('scripts')
@php $o=$shipment->originPort??$shipment->originCountry;$d=$shipment->destinationPort??$shipment->destinationCountry;$originMap=$o?['lat'=>(float)$o->latitude,'lng'=>(float)$o->longitude,'name'=>$shipment->originPort?->name??$shipment->originCountry?->name]:null;$destinationMap=$d?['lat'=>(float)$d->latitude,'lng'=>(float)$d->longitude,'name'=>$shipment->destinationPort?->name??$shipment->destinationCountry?->name]:null;$vesselMap=$shipment->vessel?['lat'=>(float)$shipment->vessel->latitude,'lng'=>(float)$shipment->vessel->longitude,'name'=>$shipment->vessel->name,'speed'=>(float)$shipment->vessel->speed]:null; @endphp
<script>document.addEventListener('DOMContentLoaded',()=>{const origin=@json($originMap),destination=@json($destinationMap),vessel=@json($vesselMap),valid=p=>p&&Number.isFinite(p.lat)&&Number.isFinite(p.lng),map=L.map('shipmentMap');L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);const bounds=[];if(valid(origin)){L.circleMarker([origin.lat,origin.lng],{radius:8,color:'#10b981',fillOpacity:1}).bindPopup(`<strong>Asal</strong><br>${origin.name}`).addTo(map);bounds.push([origin.lat,origin.lng])}if(valid(destination)){L.circleMarker([destination.lat,destination.lng],{radius:8,color:'#ef4444',fillOpacity:1}).bindPopup(`<strong>Tujuan</strong><br>${destination.name}`).addTo(map);bounds.push([destination.lat,destination.lng])}if(valid(origin)&&valid(destination))L.polyline([[origin.lat,origin.lng],[destination.lat,destination.lng]],{color:'#60a5fa',weight:3,dashArray:'8 8'}).addTo(map);if(valid(vessel)){const icon=L.divIcon({className:'',html:'<div class="ship-marker">🚢</div>',iconSize:[34,34],iconAnchor:[17,17]});L.marker([vessel.lat,vessel.lng],{icon}).bindPopup(`<strong>${vessel.name}</strong><br>Posisi simulasi saat ini<br>${vessel.speed} knot`).addTo(map).openPopup();bounds.push([vessel.lat,vessel.lng])}bounds.length>1?map.fitBounds(bounds,{padding:[45,45],maxZoom:7}):map.setView(bounds[0]||[0,0],bounds.length?6:2)});</script>
@endpush
