@extends('layouts.app')
@push('styles')<style>.booking-card{background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.08);border-radius:16px}.modal-content{background:#170f29;color:#fff}.modal-header,.modal-footer{border-color:rgba(255,255,255,.08)}</style>@endpush
@section('content')
<div class="container-fluid py-4">
 <div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 text-white fw-bold">Booking Operasional</h1><p class="text-muted mb-0">Shipment otomatis tercatat setelah booking dikonfirmasi.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#bookingModal">+ Booking Baru</button></div>
 @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
 @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
 <div class="booking-card p-4 table-responsive"><table class="table table-dark table-hover align-middle"><thead><tr><th>Booking</th><th>Pelanggan/Kargo</th><th>Rute</th><th>Jadwal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
 @forelse($bookings as $booking)<tr><td><strong>{{ $booking->booking_number }}</strong></td><td>{{ $booking->customer_name }}<div class="text-muted small">{{ $booking->cargo_description }}{{ $booking->cargo_weight ? ' · '.number_format($booking->cargo_weight).' kg':'' }}</div></td><td>{{ $booking->originCountry?->name }} → {{ $booking->destinationCountry?->name }}<div class="text-muted small">{{ $booking->vessel?->name ?? 'Kapal belum ditentukan' }}</div></td><td>{{ $booking->departure_at?->format('d M Y H:i') ?? '—' }}<div class="text-muted small">ETA {{ $booking->estimated_arrival?->format('d M Y H:i') ?? '—' }}</div></td><td><span class="badge bg-{{ $booking->status==='confirmed'?'success':($booking->status==='cancelled'?'danger':'warning') }}">{{ ucfirst($booking->status) }}</span></td><td>@if($booking->status==='draft')<form method="POST" action="{{ route('bookings.confirm',$booking) }}" onsubmit="return confirm('Konfirmasi booking dan buat shipment?')">@csrf<button class="btn btn-sm btn-success">Konfirmasi</button></form>@elseif($booking->shipment)<a class="btn btn-sm btn-outline-primary" href="{{ route('shipments.show',$booking->shipment) }}">Lihat Shipment</a>@endif</td></tr>
 @empty<tr><td colspan="6" class="text-center text-muted py-5">Belum ada booking operasional.</td></tr>@endforelse
 </tbody></table>{{ $bookings->links() }}</div>
</div>
<div class="modal fade" id="bookingModal"><div class="modal-dialog modal-xl modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('bookings.store') }}">@csrf<div class="modal-header"><h5>Booking Baru</h5><button class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
 <div class="col-md-6"><label class="form-label">Nama pelanggan</label><input class="form-control" name="customer_name" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="customer_email"></div>
 <div class="col-md-8"><label class="form-label">Deskripsi kargo</label><input class="form-control" name="cargo_description" required></div><div class="col-md-4"><label class="form-label">Berat (kg)</label><input class="form-control" type="number" min="0" step=".01" name="cargo_weight"></div>
 @foreach(['origin'=>'Asal','destination'=>'Tujuan'] as $side=>$label)<div class="col-md-3"><label class="form-label">Negara {{ $label }}</label><select class="form-select country-select" data-side="{{ $side }}" name="{{ $side }}_country_id" required><option value="">Pilih</option>@foreach($countries as $country)<option value="{{ $country->id }}">{{ $country->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Pelabuhan {{ $label }}</label><select class="form-select" name="{{ $side }}_port_id"><option value="">Opsional</option>@foreach($ports as $port)<option value="{{ $port->id }}" data-country="{{ $port->country_id }}">{{ $port->name }}</option>@endforeach</select></div>@endforeach
 <div class="col-md-4"><label class="form-label">Kapal</label><select class="form-select" name="vessel_id"><option value="">Belum ditentukan</option>@foreach($vessels as $vessel)<option value="{{ $vessel->id }}">{{ $vessel->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Keberangkatan</label><input class="form-control" type="datetime-local" name="departure_at"></div><div class="col-md-4"><label class="form-label">ETA</label><input class="form-control" type="datetime-local" name="estimated_arrival"></div>
 </div></div><div class="modal-footer"><button type="button" class="btn btn-outline-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan Draft</button></div></form></div></div>
@endsection
@push('scripts')<script>document.querySelectorAll('.country-select').forEach(c=>c.addEventListener('change',()=>{const p=c.form.elements[`${c.dataset.side}_port_id`];[...p.options].forEach((o,i)=>o.hidden=i>0&&o.dataset.country!==c.value);p.value=''}));@if($errors->any()) bootstrap.Modal.getOrCreateInstance(document.getElementById('bookingModal')).show();@endif</script>@endpush
